### ISSUE TITLE
获取账户交易列表函数的BUG

### ISSUE THREAD

**Issue by tracy4262** [swtcpro/jingtum-lib#3]
requestAccountTx函数(account:'', limit: 200)，当limit数值大于100时返回数据不全，超过100的部分是...more iems，造成bug。

![default](https://user-images.githubusercontent.com/5356688/42211129-610c4842-7ee5-11e8-8226-7b5d96c0b7ff.png)

**Comment by mousehuang** [comment]
这是使用的IDE的问题吧，“100 more items”提示你还有100条数据没有显示出来。要是全部显示的话怕你一下子看不过来。
